# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- hosts: primary
  tasks:
    - name: Deploy Required packages
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/000-install-packages.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Kubernetes
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/010-deploy-k8s.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Setup OS and K8s Clients
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/020-setup-client.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Ingress
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/030-ingress.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy NFS
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/040-nfs-provisioner.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Mariadb
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/050-mariadb.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy RabbitMQ
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/060-rabbitmq.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Memcached
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/070-memcached.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Keystone
      when: idp_backend is not defined
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/080-keystone.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Keystone with LDAP
      when: idp_backend is defined and idp_backend == "ldap"
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/ldap/080-keystone.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Heat
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/090-heat.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Horizon
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/100-horizon.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Glance
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/120-glance.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy OpenvSwitch
      when: osh_neutron_backend == 'openvswitch'
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/140-openvswitch.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy Libvirt
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/150-libvirt.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy VM Compute Kit
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/160-compute-kit.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Setup Gateway
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/170-setup-gateway.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
    - name: Deploy use the cloud
      environment:
        OSH_OPENSTACK_RELEASE: "{{ osh_openstack_release }}"
        OSH_EXTRA_HELM_ARGS: "{{ zuul_osh_extra_helm_args_relative_path | default('') }}"
        OSH_INFRA_PATH: "{{ zuul_osh_infra_relative_path | default('') }}"
        zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
      shell: |
        set -xe;
        ./tools/deployment/developer/nfs/900-use-it.sh
      args:
        chdir: "{{ zuul_osh_relative_path | default(zuul.project.src_dir) }}"
