{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}


{{- define "ceph.osd.daemonset" }}
{{- $configMapName := index . 0 }}
{{- $serviceAccountName := index . 1 }}
{{- $envAll := index . 2 }}
{{- with $envAll }}
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ceph-osd
  labels:
{{ tuple $envAll "ceph" "osd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll "ceph" "osd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "ceph" "osd" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      nodeSelector:
        {{ .Values.labels.osd.node_selector_key }}: {{ .Values.labels.osd.node_selector_value }}
      hostNetwork: true
      hostPID: true
      dnsPolicy: {{ .Values.pod.dns_policy }}
      initContainers:
{{ tuple $envAll "osd" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: ceph-init-dirs
{{ tuple $envAll "ceph_osd" | include "helm-toolkit.snippets.image" | indent 10 }}
          command:
            - /tmp/init-dirs.sh
          env:
          # NOTE(portdirect): These environment variables will be populated
          # dynamicly at the point of render.
          # - name: OSD_DEVICE
          #   value: /dev/sdb
          # - name: OSD_FORCE_ZAP
          #   value: false
          # - name: OSD_DB_DEVICE:
          #   value: empty string
            - name: CLUSTER
              value: "ceph"
          volumeMounts:
            - name: ceph-osd-bin
              mountPath: /tmp/init-dirs.sh
              subPath: init-dirs.sh
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: pod-run
              mountPath: /run
              readOnly: false
        - name: osd-init
{{ tuple $envAll "ceph_osd" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.osd | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          securityContext:
            privileged: true
          env:
          # NOTE(portdirect): These environment variables will be populated
          # dynamicly at the point of render and added to all containers in the
          # pod
          # - name: OSD_DEVICE
          #   value: /dev/sdb
          # - name: OSD_FORCE_ZAP
          #   value: false
          # - name: OSD_DB_DEVICE:
          #   value: empty string
            - name: CLUSTER
              value: "ceph"
          command:
            - /tmp/osd-init.sh
          volumeMounts:
            - name: ceph-osd-bin
              mountPath: /tmp/osd-init.sh
              subPath: osd-init.sh
              readOnly: true
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
              subPath: ceph.keyring
              readOnly: false
            - name: devices
              mountPath: /dev
              readOnly: false
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: pod-run
              mountPath: /run
              readOnly: false
            - name: run-lvm
              mountPath: /run/lvm
              readOnly: false
            - name: ceph-osd-bin
              mountPath: /etc/lvm/lvmlocal.conf
              subPath: lvmlocal.conf
              readOnly: true
      containers:
        - name: osd-pod
{{ tuple $envAll "ceph_osd" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.osd | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          securityContext:
            privileged: true
          env:
          # NOTE(portdirect): These environment variables will be populated
          # dynamicly at the point of render.
          # - name: OSD_DEVICE
          #   value: /dev/sdb
          # - name: OSD_FORCE_ZAP
          #   value: false
          # - name: OSD_DB_DEVICE:
          #   value: empty string
            - name: CLUSTER
              value: "ceph"
          command:
            - /tmp/osd-start.sh
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/osd-stop.sh
          livenessProbe:
           exec:
            command:
             - /tmp/osd-check.sh
             - liveness
           initialDelaySeconds: 120
           periodSeconds: 60
          readinessProbe:
           exec:
            command:
             - /tmp/osd-check.sh
             - readiness
           initialDelaySeconds: 60
           periodSeconds: 60
          volumeMounts:
            - name: ceph-osd-bin
              mountPath: /tmp/osd-start.sh
              subPath: osd-start.sh
              readOnly: true
            - name: ceph-osd-bin
              mountPath: /tmp/osd-check.sh
              subPath: osd-check.sh
              readOnly: true
            - name: ceph-osd-bin
              mountPath: /tmp/osd-stop.sh
              subPath: osd-stop.sh
              readOnly: true
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
              subPath: ceph.keyring
              readOnly: false
            - name: devices
              mountPath: /dev
              readOnly: false
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: pod-run
              mountPath: /run
              readOnly: false
            - name: run-lvm
              mountPath: /run/lvm
              readOnly: false
            - name: varlog
              mountPath: /var/log/ceph
            - name: ceph-osd-bin
              mountPath: /etc/lvm/lvmlocal.conf
              subPath: lvmlocal.conf
              readOnly: true
        {{ if .Values.logging.fluentd }}
        - name: fluentbit-sidecar
{{ tuple $envAll "fluentbit" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.fluentbit | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          command:
            - /tmp/fluentbit-sidecar.sh
          volumeMounts:
            - name: ceph-osd-bin
              mountPath: /tmp/fluentbit-sidecar.sh
              subPath: fluentbit-sidecar.sh
              readOnly: true
            - name: varlog
              mountPath: /var/log/ceph
            - name: ceph-etc
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
              readOnly: true
            - name: ceph-etc
              mountPath: /fluent-bit/etc/parsers.conf
              subPath: parsers.conf
              readOnly: true
        {{ end }}
      volumes:
        - name: devices
          hostPath:
            path: /dev
        - name: run-lvm
          hostPath:
            path: /run/lvm
        - name: pod-var-lib-ceph
          emptyDir: {}
        - name: varlog
          emptyDir: {}
        - name: pod-run
          emptyDir:
            medium: "Memory"
        - name: ceph-osd-bin
          configMap:
            name: ceph-osd-bin
            defaultMode: 0555
        - name: ceph-etc
          configMap:
            name: {{ $configMapName }}
            defaultMode: 0444
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.osd }}

{{- end }}
{{- end }}

{{- if .Values.manifests.daemonset_osd }}
{{- $configMapName := "ceph-etc" }}
{{- $serviceAccountName := "ceph-osd"}}
{{ tuple . "osd" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{- $daemonset_yaml := list $configMapName $serviceAccountName . | include "ceph.osd.daemonset" | toString }}
{{- list $daemonset_yaml . | include "ceph.utils.osd_daemonset_list" }}
{{- end }}
