{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.daemonset_osd_maint }}
{{- $envAll := . }}
{{- $serviceAccountName := "ceph-osd-maint"}}
{{ tuple . "osd-maint" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ceph-osd-maint
  labels:
{{ tuple $envAll "ceph" "osd-maint" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll "ceph" "osd-maint" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "ceph" "osd-maint" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
{{ dict "envAll" $envAll "application" "osd_maint" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      serviceAccountName: {{ $serviceAccountName }}
      nodeSelector:
        {{ .Values.labels.osd_maint.node_selector_key }}: {{ .Values.labels.osd_maint.node_selector_value | quote }}
      hostNetwork: true
      hostPID: true
      dnsPolicy: {{ .Values.pod.dns_policy }}
      initContainers:
{{ tuple $envAll "osd-maint" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: maint
{{ tuple $envAll "ceph_osd" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.osd_maint | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "osd_maint" "container" "maint" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          securityContext:
            privileged: true
          env:
            - name: CLUSTER
              value: "ceph"
          command:
            - /usr/bin/sleep
          args:
            - '3650d'
          volumeMounts:
            # Volume mounts are identical to main OSD container (see cr-osds.yaml)
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-osd-bin
              mountPath: /tmp/osd-start.sh
              subPath: osd-start.sh
              readOnly: true
            - name: ceph-osd-bin
              mountPath: /tmp/osd-check.sh
              subPath: osd-check.sh
              readOnly: true
            - name: ceph-osd-bin
              mountPath: /tmp/osd-stop.sh
              subPath: osd-stop.sh
              readOnly: true
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
              subPath: ceph.keyring
              readOnly: false
            - name: devices
              mountPath: /dev
              readOnly: false
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: run-lvm
              mountPath: /run/lvm
              readOnly: false
            - name: varlog
              mountPath: /var/log/ceph
            - name: ceph-osd-bin
              mountPath: /etc/lvm/lvmlocal.conf
              subPath: lvmlocal.conf
              readOnly: true
            - name: ceph-osd-bin
              mountPath: /usr/local/sbin/smartctl
              subPath: smartctl
              readOnly: true
            - name: ceph-osd-bin
              mountPath: /etc/sudoers.d/ceph-osd-smartctl
              subPath: sudoers.d-ceph-osd-smartctl
            # Maint container specific volume mounts
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
      volumes:
        # Volumes are identical to main OSD container (see cr-osds.yaml)
        - name: pod-tmp
          emptyDir: {}
        - name: pod-run
          emptyDir:
            medium: "Memory"
        - name: pod-etc-ceph
          emptyDir: {}
        - name: devices
          hostPath:
            path: {{ .Values.conf.storage.dev_path }}
        - name: run-lvm
          hostPath:
            path: /run/lvm
        - name: pod-var-lib-ceph
          emptyDir: {}
        - name: varlog
          emptyDir: {}
        - name: ceph-osd-bin
          configMap:
            name: ceph-osd-bin
            defaultMode: 0555
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.osd }}
        # Maint container specific volumes
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
{{- end }}
