{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if and .Values.manifests.daemonset_mon .Values.deployment.ceph }}
{{- $envAll := . }}

{{- $serviceAccountName := "ceph-mon"}}
{{ tuple $envAll "mon" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceAccountName }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $envAll.Release.Namespace }}
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ceph-mon
  labels:
{{ tuple $envAll "ceph" "mon" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll "ceph" "mon" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll "mon" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "ceph" "mon" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
{{ dict "envAll" $envAll "application" "mon" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      serviceAccountName: {{ $serviceAccountName }}
      nodeSelector:
        {{ .Values.labels.mon.node_selector_key }}: {{ .Values.labels.mon.node_selector_value | quote }}
    {{- if .Values.tolerations.mon }}
      tolerations:
{{ toYaml .Values.tolerations.mon | indent 8 }}
    {{- end }}
      hostNetwork: true
      dnsPolicy: {{ .Values.pod.dns_policy }}
      initContainers:
{{ tuple $envAll "mon" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: init-dirs
{{ tuple $envAll "ceph_mon" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "mon" "container" "init_dirs" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/init-dirs.sh
          env:
            - name: CLUSTER
              value: "ceph"
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-mon-bin
              mountPath: /tmp/init-dirs.sh
              subPath: init-dirs.sh
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
      containers:
        - name: mon
{{ tuple $envAll "ceph_mon" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.mon | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "mon" "container" "mon" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          env:
            - name: CLUSTER
              value: "ceph"
            - name: MONMAP
              value: /var/lib/ceph/mon/monmap
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CEPH_PUBLIC_NETWORK
              value: {{ .Values.network.public | quote }}
            - name: KUBECTL_PARAM
              value: {{ tuple $envAll "ceph" "mon" | include "helm-toolkit.snippets.kubernetes_kubectl_params" | indent 10 }}
            - name: MON_PORT
              value: {{ tuple "ceph_mon" "internal" "mon" $envAll | include "helm-toolkit.endpoints.endpoint_port_lookup" | quote }}
            - name: MON_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /tmp/mon-start.sh
          lifecycle:
            preStop:
                exec:
                  command:
                    - /tmp/mon-stop.sh
          ports:
            - containerPort: {{ tuple "ceph_mon" "internal" "mon" $envAll | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
            - containerPort: {{ tuple "ceph_mon" "v2" "mon" $envAll | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
          livenessProbe:
           exec:
            command:
             - /tmp/mon-check.sh
             - liveness
           initialDelaySeconds: 360
           periodSeconds: 180
          readinessProbe:
           exec:
            command:
             - /tmp/mon-check.sh
             - readiness
           initialDelaySeconds: 60
           periodSeconds: 60
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-mon-bin
              mountPath: /tmp/mon-start.sh
              subPath: mon-start.sh
              readOnly: true
            - name: ceph-mon-bin
              mountPath: /tmp/mon-stop.sh
              subPath: mon-stop.sh
              readOnly: true
            - name: ceph-mon-bin
              mountPath: /tmp/mon-check.sh
              subPath: mon-check.sh
              readOnly: true
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
            - name: ceph-mon-keyring
              mountPath: /etc/ceph/ceph.mon.keyring.seed
              subPath: ceph.mon.keyring
              readOnly: true
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
              subPath: ceph.keyring
              readOnly: true
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds/ceph.keyring
              subPath: ceph.keyring
              readOnly: true
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw/ceph.keyring
              subPath: ceph.keyring
              readOnly: true
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd/ceph.keyring
              subPath: ceph.keyring
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: varlog
              mountPath: /var/log/ceph
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: pod-run
          emptyDir:
           medium: "Memory"
        - name: pod-etc-ceph
          emptyDir: {}
        - name: varlog
          emptyDir: {}
        - name: ceph-mon-bin
          configMap:
            name: ceph-mon-bin
            defaultMode: 0555
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: pod-var-lib-ceph
          hostPath:
            path: {{ .Values.conf.storage.mon.directory }}
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
        - name: ceph-mon-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mon }}
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.osd }}
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mds }}
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.rgw }}
        - name: ceph-bootstrap-rbd-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.rbd }}
{{- end }}
