{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.job_rbd_pool }}
{{- if .Values.deployment.ceph }}
{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.rbd_pool }}

{{- $serviceAccountName := "ceph-rbd-pool" }}
{{ tuple $envAll $dependencies $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ceph-rbd-pool
spec:
  template:
    metadata:
      name: ceph-rbd-pool
      labels:
{{ tuple $envAll "ceph" "rbd-pool" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      restartPolicy: OnFailure
      affinity:
{{ tuple $envAll "ceph" "mgr" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.mgr.node_selector_key }}: {{ .Values.labels.mgr.node_selector_value }}
    {{- if .Values.tolerations.jobs }}
      tolerations:
{{ toYaml .Values.tolerations.jobs | indent 8 }}
    {{- end }}
      initContainers:
{{ tuple $envAll $dependencies list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: ceph-rbd-pool
          image: {{ .Values.images.tags.ceph_daemon }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.mgr | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: RBD_POOL_PG
              value: "128"
          command:
            - /ceph_rbd_pool.sh
          volumeMounts:
            - name: ceph-bin
              mountPath: /ceph_rbd_pool.sh
              subPath: ceph_rbd_pool.sh
              readOnly: true
            - name: ceph-bin
              mountPath: /variables_entrypoint.sh
              subPath: variables_entrypoint.sh
              readOnly: true
            - name: ceph-bin
              mountPath: /common_functions.sh
              subPath: common_functions.sh
              readOnly: true
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: pod-run
              mountPath: /run
              readOnly: false
      volumes:
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: ceph-bin
          configMap:
            name: ceph-bin
            defaultMode: 0555
        - name: pod-var-lib-ceph
          emptyDir: {}
        - name: pod-run
          emptyDir:
            medium: "Memory"
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
{{- end }}
{{- end }}
