# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for mariadb.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

release_group: null

images:
  tags:
    # NOTE: if you update from 10.2.13 please look at
    # https://review.openstack.org/#/q/Ifd09d7effe7d382074ca9e6678df36bdd4bce0af
    # and check whether it's still needed
    mariadb: docker.io/mariadb:10.2.13
    ingress: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
    error_pages: gcr.io/google_containers/defaultbackend:1.0
    prometheus_create_mysql_user: docker.io/mariadb:10.2.13
    prometheus_mysql_exporter: docker.io/prom/mysqld-exporter:v0.10.0
    prometheus_mysql_exporter_helm_tests: docker.io/openstackhelm/heat:newton
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    image_repo_sync: docker.io/docker:17.07.0
  pull_policy: "IfNotPresent"
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

labels:
  server:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  ingress:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  prometheus_mysql_exporter:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  error_server:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

pod:
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
  replicas:
    server: 1
    ingress: 1
    error_page: 1
    prometheus_mysql_exporter: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
    termination_grace_period:
      prometheus_mysql_exporter:
        timeout: 30
      error_pages:
        timeout: 10
    disruption_budget:
      mariadb:
        min_available: 0
  resources:
    enabled: false
    prometheus_mysql_exporter:
      limits:
        memory: "1024Mi"
        cpu: "2000m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    server:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      tests:
        limits:
          memory: "1024Mi"
          cpu: "2000m"
        requests:
          memory: "128Mi"
          cpu: "100m"
      prometheus_create_mysql_user:
        limits:
          memory: "1024Mi"
          cpu: "2000m"
        requests:
          memory: "128Mi"
          cpu: "100m"
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - mariadb-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    error_pages:
      jobs: null
    ingress:
      jobs: null
      services:
        - endpoint: error_pages
          service: oslo_db
    mariadb:
      jobs: null
      services: null
    prometheus_create_mysql_user:
      services:
        - endpoint: internal
          service: oslo_db
    prometheus_mysql_exporter:
      jobs:
        - exporter-create-sql-user
      services:
        - endpoint: internal
          service: oslo_db
    prometheus_mysql_exporter_tests:
      services:
        - endpoint: internal
          service: prometheus_mysql_exporter
        - endpoint: internal
          service: monitoring
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry

force_bootstrap: false

volume:
  chown_on_start: true
  enabled: true
  class_name: general
  size: 5Gi



conf:
  ingress: null

database:
  config_override: null
  # Any configuration here will override the base config.
  # config_override: |-
  #   [mysqld]
  #   wsrep_slave_threads=1

monitoring:
  prometheus:
    enabled: false
    mysqld_exporter:
      scrape: true

network:
  prometheus_mysql_exporter:
    port: 9104

# typically overridden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  monitoring:
    name: prometheus
    namespace: null
    hosts:
      default: prom-metrics
      public: prometheus
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    port:
      api:
        default: 9090
        public: 80
  prometheus_mysql_exporter:
    namespace: null
    auth:
      user:
        username: exporter
        password: password
    hosts:
      default: mysql-exporter
    host_fqdn_override:
      default: null
    path:
      default: /metrics
    scheme:
      default: 'http'
    port:
      metrics:
        default: 9104
  oslo_db:
    namespace: null
    auth:
      admin:
        username: root
        password: password
      exporter:
        username: exporter
        password: password
    hosts:
      default: mariadb
      direct: mariadb-server
      discovery: mariadb-discovery
      error_pages: mariadb-ingress-error-pages
    host_fqdn_override:
      default: null
    path: null
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
      wsrep:
        default: 4567

manifests:
  configmap_bin: true
  configmap_etc: true
  configmap_services_tcp: true
  deployment_error: true
  deployment_ingress: true
  job_image_repo_sync: true
  monitoring:
    prometheus:
      configmap_bin: true
      deployment_exporter: true
      job_user_create: true
      secret_etc: true
      service_exporter: true
  pdb_server: true
  secret_db: true
  secret_etc: true
  service_discovery: true
  service_ingress: true
  service_error: true
  service: true
  statefulset: true
